### ISSUE TITLE
onSlidingComplete not getting called on Android

### ISSUE THREAD

**Issue by tarangill** [callstack/react-native-slider#239]
## Environment

System:
    OS: Linux 4.18 CentOS Linux 8 (Core)
    CPU: (20) x64 Intel(R) Core(TM) i9-9820X CPU @ 3.30GHz
    Memory: 92.80 GB / 125.34 GB
    Shell: 4.4.19 - /bin/bash
  Binaries:
    Node: 12.16.1 - /usr/local/bin/node
    Yarn: Not Found
    npm: 6.14.8 - /usr/local/bin/npm
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
  IDEs:
    Android Studio: Not Found
  Languages:
    Java: 1.8.0_252 - /usr/bin/javac
    Python: 3.6.8 - /usr/bin/python
  npmPackages:
    @react-native-community/cli: Not Found
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    *react-native*: Not Found

## Description
onSlidingComplete does not get called on Android. I have version 3.0.3.

**Comment by duttasuraj93** [comment]
@tarangill I had the same issue where I was importing Slider from react-native instead of from the community slider

Eg.
`import Slider from '@react-native-community/slider';`

instead of
`import { Slider } from 'react-native';`

you can try this and see if it starts working. Not sure otherwise since you did not upload any code
