### ISSUE TITLE
Slider manipulation results in crashes for react-native-windows when no step is specified

### ISSUE THREAD

**Issue by chrisfromwork** [callstack/react-native-slider#256]
## Environment

* Building on a PC with visual studio 2019
* Using react-native-windows@0.64.0-preview.5
* Using @react-native-community/slider@4.0.0-rc.2

## Description

If you don't specify a step value, no default is set. This then causes xaml range value component to generate errors

## Reproducible Demo

* Setup a react-native-windows project
* Add @react-native-community/slider@4.0.0-rc.2 as a dependency and register the package in your project's app.cpp file
* Add a slider to your app, avoid specifying a step value
* Manipulate the slider

#### Observed behavior
The application crashes because no step value is set

#### Expected behavior
The application falls back to using a default step value

**Comment by rectified95** [comment]
fyi @BartoszKlonowski I already have a fix

**Comment by BartoszKlonowski** [comment]
@rectified95 I didn't notice your comment, but why have you been working on an issue which has already a developer assigned to it?

**Comment by rectified95** [comment]
@BartoszKlonowski The issue was spotted by a consumer from Hololens. along with the autolinking problem. He first reached out to me and only created these issues for tracking/visibility. I don't have the privileges to assign issues in this repo, so couldn't self-assign, and later on didn't check that you had it on you. We wanted to fix it sooner than later so I went ahead and did it.
