### ISSUE TITLE
updateValue on ref for all platforms

### ISSUE THREAD

**Issue by bigcupcoffee** [callstack/react-native-slider#378]
I'd really like to be able to reset Slider's position if I need to reset or set Slider's value programmatically without doing some hacky workaround with `key` property to force an unmount, if possible 🙂

**Comment by BartoszKlonowski** [comment]
Hello @bigcupcoffee!
Currently **it is possible** to control the Slider using the `value` property (since v4.2.0). So if you want to set it in any position you can by just updating the value programmaticaly. Let me know if you encounter any issues with it as it is still a quite new feature.
When it comes to resetting the Slider position - you will have to do it "manually" by keeping the initial value in some variable and setting the Slider's `value` with the initial one when you want the slider to reset.

**Comment by bigcupcoffee** [comment]
@BartoszKlonowski hello. Prop's docs misled me at this point although I'm pretty sure I tried it on some older version, which I had to upgrade from because of tap behavior anyway, so yeah it seems to work now.
 Thanks for quick response, I'd recommend to update docs and JSDoc on the lib, which for some reason wasn't done on 4.2.0 release. You can close the issue

**Comment by BartoszKlonowski** [comment]
Glad to hear that it works!
I will close this now and open a new issue to update the docs everywhere about the controlled value, thank you for pointing that out 👍
