### ISSUE TITLE
plzz add onRightSlide and onLeftSlide options thats why we detect whether left swipe right swipe

### ISSUE THREAD

**Issue by GouravNainwaya** [callstack/react-native-slider#493]

**Comment by BartoszKlonowski** [comment]
Hello @GouravNainwaya, thanks for the proposal!
This feature seems to be implementable, however it would require some additional thinking and proper API to be figure out whether this information should come within the event, or as a separate event.

However, for the time being you can use the value comparison to deduce whether it increases or decreases while dragging, which will mean that user is dragging the thumb left or right.
Something like that:

https://user-images.githubusercontent.com/70535775/217774366-737416ca-16a2-4c17-9a43-2c6050cc0b98.mov

Let me keep it open to see whether there are more comments or reactions from others so that I know whether this feature is really wanted, but let me put a `wontfix` label on that so I can keep have it marked somehow.

**Comment by BartoszKlonowski** [comment]
@GouravNainwaya Please let me know if the suggested solution works for you?

**Comment by BartoszKlonowski** [comment]
Closing due to lack of author's response, lack of interests within the community and due to the fact that this feature is also very easy to be implemented while utilizing Slider library (example is shown in [recent comment](https://github.com/callstack/react-native-slider/issues/493#issuecomment-1423895146)).
In case of further need or questions please comment.
