### ISSUE TITLE
Is there a way to have the slider button start in the middle and have the fill color also start from the middle?

### ISSUE THREAD

**Issue by itsgeraldwang** [callstack/react-native-slider#612]
## Ask your Question

See title. I would like to create something like this design. Is it possible with the current features offered?

<img width="607" alt="Screen Shot 2024-06-22 at 6 32 19 PM" src="https://github.com/callstack/react-native-slider/assets/42704142/260d35ab-f13a-4f54-bedd-5df15c9c5188">

**Comment by BartoszKlonowski** [comment]
Hello @itsgeraldwang, thanks for reaching out!
There is the `trackImage` feature which would allow you to replace the track with the image you would have to prepare according to your design.
Another option, more complicated though, would be to use `StepMarker`:
Prepare the step marker transparent for each step, with their layout being the height of the track's width,
calculate the difference between the middle step and the thumbs position (by using the `value` prop of the thumb and the `StepMarker`),
change the style of those steps that are in between the middle and thumb's position, so that the desired gradient is rendered.

Give it a try, or let me know if you have some more questions/issues.
Also, if you'll have some findings or conclusions, I'm happy to hear.

**Comment by itsgeraldwang** [comment]
Thanks for the response, I'll try playing around with that and get back to you if it works or if I have any other questions.

**Comment by itsgeraldwang** [comment]
I was able to get it to work by overlaying a track over the slider itself and adjusting the width of the overlayed track using the value prop from the slider. One more question though:

Is there any way to adjust the styling of the slider button such as size and shape? I see there is a thumb image prop but I would rather style the button through native styling instead of using an image.

**Comment by itsgeraldwang** [comment]
Nvm, read through some of the pending issues and looks like button styling isn't a feature yet. I'll mark this as resolved since the original question has been answered, but +1 to having a way to style the thumb!
