### ISSUE TITLE
cannot increse the height of slider like borderWith

### ISSUE THREAD

**Issue by saqibrazaq1** [callstack/react-native-slider#633]
## Describe the Feature

cannot increase the width of slider

Add this feature

**Comment by BartoszKlonowski** [comment]
Hello @saqibrazaq1, let me understand what you are asking for:

* The width of the slider, means the length of the track?
If so, you can use the `width` of styling, as: `<Slider style={{ width: 250 }} />`
* The width of the thumb?
To customize the default (system, native) thumb of the slider is currently not supported, but you can use your own component that would be rendered instead of default thumb, or you can also use the image that would replace the thumb.

Let me know please.

**Comment by saqibrazaq1** [comment]
i mean height like like border 1px or border 2px and borderWidth 3 the line of slider is thin i want a thick line slider
![slider-preview](https://github.com/user-attachments/assets/451aa313-85cd-4755-a8a6-ef3fd15fcee5)

**Comment by AyoCodess** [comment]
> i mean height like like border 1px or border 2px and borderWidth 3 the line of slider is thin i want a thick line slider ![slider-preview](https://private-user-images.githubusercontent.com/136598548/365671312-451aa313-85cd-4755-a8a6-ef3fd15fcee5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1NjE1NjYsIm5iZiI6MTcyNjU2MTI2NiwicGF0aCI6Ii8xMzY1OTg1NDgvMzY1NjcxMzEyLTQ1MWFhMzEzLTg1Y2QtNDc1NS1hOGE2LWVmM2ZkMTVmY2VlNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QwODIxMDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODkxNDJkMTQxMjIxNzU1YTk5ZjJmOTdjZDcxNDA3MTEzMjNmMTVjNTQ1OWQ5YzU5N2Q0ZmY3ZjAxNjJlMGM3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.0qxOcQ5Zx4c5kU8fpODO1z270Xe8s_NN5gTz5lgRm3Q)

did you find a solution?

**Comment by andrehadianto** [comment]
+1 to this issue

**Comment by petrichor-hl** [comment]
+1

**Comment by modbender** [comment]
Can't a feature to pass styles to parts of sliders be created?

**Comment by theBGuy** [comment]
+1

**Comment by luannguyenQV** [comment]
+1 for this issue

**Comment by dule-vikki** [comment]
+1

**Comment by Aklile-Yilma** [comment]
+1

**Comment by draggie** [comment]
I have been working extensively on achieving custom height (thickness) for the slider, as requested. While I managed to make some progress, such as drawing custom drawables, I encountered persistent challenges. These include synchronisation issues with colors and incompatibility between the custom drawable and the default thumb, which often results in the components visually merging into a single element.

Most of the suggested solutions recommend using the Material Slider instead of the current implementation based on Material SeekBar. While I even attempted to create an alternative implementation, I faced significant obstacles due to mismatches in behavior and design elements, which ultimately led me to abandon the effort.

Given these challenges, I believe for now this is not something we can implement, but maybe at some point we will consider migrating to material implementation.
